import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageManager {
  static const String _languageKey = 'selected_language';
  
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'SEHAT',
      'app_subtitle': 'Smart E-Health Access for Telemedicine',
      'select_language': 'Select Language',
      'punjabi': 'ਪੰਜਾਬੀ',
      'hindi': 'हिंदी',
      'english': 'English',
      'continue': 'Continue',
      'welcome': 'Welcome to SEHAT',
      'welcome_subtitle': 'Your gateway to accessible healthcare',
      'book_consultation': 'Book Consultation',
      'check_medicine': 'Check Medicine Availability',
      'symptom_checker': 'Symptom Checker',
      'health_records': 'Health Records',
      'available_doctors': 'Available Doctors',
      'general_practitioner': 'General Practitioner',
      'specialist': 'Specialist',
      'video_call': 'Video Call',
      'audio_call': 'Audio Call',
      'search_medicine': 'Search Medicine',
      'medicine_name': 'Medicine Name',
      'search': 'Search',
      'nearby_pharmacies': 'Nearby Pharmacies',
      'in_stock': 'In Stock',
      'out_of_stock': 'Out of Stock',
      'start_symptom_check': 'Start Symptom Check',
      'answer_questions': 'Answer a few simple questions',
      'previous_prescriptions': 'Previous Prescriptions',
      'medical_history': 'Medical History',
      'offline_available': 'Available Offline',
      'back': 'Back',
      'next': 'Next',
      'finish': 'Finish',
      'book_now': 'Book Now',
      'view_profile': 'View Profile',
      'rating': 'Rating',
      'experience': 'Years Experience',
      'consultation_fee': 'Consultation Fee',
      'available_today': 'Available Today',
      'available_tomorrow': 'Available Tomorrow',
      'join_consultation': 'Join Consultation',
      'prescription_received': 'Prescription Received',
      'save_to_records': 'Save to Health Records',
      'symptoms': 'Symptoms',
      'possible_conditions': 'Possible Conditions',
      'recommendations': 'Recommendations',
      'consult_doctor': 'Consult a Doctor',
      'home_remedies': 'Home Remedies',
      'pharmacy_name': 'Pharmacy Name',
      'distance': 'Distance',
      'contact': 'Contact',
      'address': 'Address',
      'prescription_date': 'Prescription Date',
      'doctor_name': 'Doctor Name',
      'medicines': 'Medicines',
      'dosage': 'Dosage',
      'duration': 'Duration',
      'notes': 'Notes',
    },
    'hi': {
      'app_title': 'सहात',
      'app_subtitle': 'टेलीमेडिसिन के लिए स्मार्ट ई-हेल्थ एक्सेस',
      'select_language': 'भाषा चुनें',
      'punjabi': 'ਪੰਜਾਬੀ',
      'hindi': 'हिंदी',
      'english': 'English',
      'continue': 'जारी रखें',
      'welcome': 'सहात में आपका स्वागत है',
      'welcome_subtitle': 'सुलभ स्वास्थ्य सेवा का आपका द्वार',
      'book_consultation': 'परामर्श बुक करें',
      'check_medicine': 'दवा की उपलब्धता जांचें',
      'symptom_checker': 'लक्षण जांचकर्ता',
      'health_records': 'स्वास्थ्य रिकॉर्ड',
      'available_doctors': 'उपलब्ध डॉक्टर',
      'general_practitioner': 'सामान्य चिकित्सक',
      'specialist': 'विशेषज्ञ',
      'video_call': 'वीडियो कॉल',
      'audio_call': 'ऑडियो कॉल',
      'search_medicine': 'दवा खोजें',
      'medicine_name': 'दवा का नाम',
      'search': 'खोजें',
      'nearby_pharmacies': 'पास की दवा की दुकानें',
      'in_stock': 'स्टॉक में',
      'out_of_stock': 'स्टॉक खत्म',
      'start_symptom_check': 'लक्षण जांच शुरू करें',
      'answer_questions': 'कुछ सरल प्रश्नों के उत्तर दें',
      'previous_prescriptions': 'पिछले नुस्खे',
      'medical_history': 'चिकित्सा इतिहास',
      'offline_available': 'ऑफलाइन उपलब्ध',
      'back': 'वापस',
      'next': 'आगे',
      'finish': 'समाप्त',
      'book_now': 'अभी बुक करें',
      'view_profile': 'प्रोफाइल देखें',
      'rating': 'रेटिंग',
      'experience': 'वर्षों का अनुभव',
      'consultation_fee': 'परामर्श शुल्क',
      'available_today': 'आज उपलब्ध',
      'available_tomorrow': 'कल उपलब्ध',
      'join_consultation': 'परामर्श में शामिल हों',
      'prescription_received': 'नुस्खा प्राप्त हुआ',
      'save_to_records': 'स्वास्थ्य रिकॉर्ड में सहेजें',
      'symptoms': 'लक्षण',
      'possible_conditions': 'संभावित स्थितियां',
      'recommendations': 'सुझाव',
      'consult_doctor': 'डॉक्टर से परामर्श करें',
      'home_remedies': 'घरेलू उपचार',
      'pharmacy_name': 'दवा की दुकान का नाम',
      'distance': 'दूरी',
      'contact': 'संपर्क',
      'address': 'पता',
      'prescription_date': 'नुस्खा तिथि',
      'doctor_name': 'डॉक्टर का नाम',
      'medicines': 'दवाएं',
      'dosage': 'खुराक',
      'duration': 'अवधि',
      'notes': 'नोट्स',
    },
    'pa': {
      'app_title': 'ਸਹਾਤ',
      'app_subtitle': 'ਟੈਲੀਮੈਡੀਸਨ ਲਈ ਸਮਾਰਟ ਈ-ਹੈਲਥ ਐਕਸੈਸ',
      'select_language': 'ਭਾਸ਼ਾ ਚੁਣੋ',
      'punjabi': 'ਪੰਜਾਬੀ',
      'hindi': 'हिंदी',
      'english': 'English',
      'continue': 'ਜਾਰੀ ਰੱਖੋ',
      'welcome': 'ਸਹਾਤ ਵਿੱਚ ਤੁਹਾਡਾ ਸਵਾਗਤ ਹੈ',
      'welcome_subtitle': 'ਸੁਲਭ ਸਿਹਤ ਸੇਵਾਵਾਂ ਦਾ ਤੁਹਾਡਾ ਦਰਵਾਜ਼ਾ',
      'book_consultation': 'ਸਲਾਹ ਬੁੱਕ ਕਰੋ',
      'check_medicine': 'ਦਵਾਈ ਦੀ ਉਪਲਬਧਤਾ ਜਾਂਚੋ',
      'symptom_checker': 'ਲੱਛਣ ਜਾਂਚਕਰਤਾ',
      'health_records': 'ਸਿਹਤ ਰਿਕਾਰਡ',
      'available_doctors': 'ਉਪਲਬਧ ਡਾਕਟਰ',
      'general_practitioner': 'ਆਮ ਡਾਕਟਰ',
      'specialist': 'ਮਾਹਿਰ',
      'video_call': 'ਵੀਡੀਓ ਕਾਲ',
      'audio_call': 'ਆਡੀਓ ਕਾਲ',
      'search_medicine': 'ਦਵਾਈ ਖੋਜੋ',
      'medicine_name': 'ਦਵਾਈ ਦਾ ਨਾਮ',
      'search': 'ਖੋਜੋ',
      'nearby_pharmacies': 'ਨੇੜਲੀਆਂ ਦਵਾਈ ਦੀਆਂ ਦੁਕਾਨਾਂ',
      'in_stock': 'ਸਟਾਕ ਵਿੱਚ',
      'out_of_stock': 'ਸਟਾਕ ਖਤਮ',
      'start_symptom_check': 'ਲੱਛਣ ਜਾਂਚ ਸ਼ੁਰੂ ਕਰੋ',
      'answer_questions': 'ਕੁਝ ਸਧਾਰਨ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦਿਓ',
      'previous_prescriptions': 'ਪਿਛਲੇ ਨੁਸਖੇ',
      'medical_history': 'ਡਾਕਟਰੀ ਇਤਿਹਾਸ',
      'offline_available': 'ਆਫਲਾਈਨ ਉਪਲਬਧ',
      'back': 'ਵਾਪਸ',
      'next': 'ਅੱਗੇ',
      'finish': 'ਸਮਾਪਤ',
      'book_now': 'ਹੁਣੇ ਬੁੱਕ ਕਰੋ',
      'view_profile': 'ਪ੍ਰੋਫਾਈਲ ਦੇਖੋ',
      'rating': 'ਰੇਟਿੰਗ',
      'experience': 'ਸਾਲਾਂ ਦਾ ਤਜਰਬਾ',
      'consultation_fee': 'ਸਲਾਹ ਫੀਸ',
      'available_today': 'ਅੱਜ ਉਪਲਬਧ',
      'available_tomorrow': 'ਕੱਲ ਉਪਲਬਧ',
      'join_consultation': 'ਸਲਾਹ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ',
      'prescription_received': 'ਨੁਸਖਾ ਪ੍ਰਾਪਤ ਹੋਇਆ',
      'save_to_records': 'ਸਿਹਤ ਰਿਕਾਰਡ ਵਿੱਚ ਸੇਵ ਕਰੋ',
      'symptoms': 'ਲੱਛਣ',
      'possible_conditions': 'ਸੰਭਾਵਿਤ ਹਾਲਤਾਂ',
      'recommendations': 'ਸਿਫਾਰਸ਼ਾਂ',
      'consult_doctor': 'ਡਾਕਟਰ ਨਾਲ ਸਲਾਹ ਕਰੋ',
      'home_remedies': 'ਘਰੇਲੂ ਉਪਚਾਰ',
      'pharmacy_name': 'ਦਵਾਈ ਦੁਕਾਨ ਦਾ ਨਾਮ',
      'distance': 'ਦੂਰੀ',
      'contact': 'ਸੰਪਰਕ',
      'address': 'ਪਤਾ',
      'prescription_date': 'ਨੁਸਖਾ ਤਾਰੀਖ',
      'doctor_name': 'ਡਾਕਟਰ ਦਾ ਨਾਮ',
      'medicines': 'ਦਵਾਈਆਂ',
      'dosage': 'ਖੁਰਾਕ',
      'duration': 'ਮਿਆਦ',
      'notes': 'ਨੋਟਸ',
    },
  };

  static String getCurrentLanguage() {
    return 'en'; // Default language
  }

  static String translate(String key, [String? language]) {
    final lang = language ?? getCurrentLanguage();
    return _translations[lang]?[key] ?? _translations['en']![key] ?? key;
  }

  static Future<void> setLanguage(String languageCode) async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_languageKey, languageCode);
  }

  static Future<String> getLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    return prefs.getString(_languageKey) ?? 'en';
  }
}
